### ISSUE TITLE
warnings from ndarray alerting to deprecated method

### ISSUE THREAD

**Issue by jj-github-jj** [l-johnston/autolv#3]
warning message 
  pyenv-win\versions\3.9.1\lib\site-packages\autolv\datatypes.py:148: VisibleDeprecationWarning:

Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.

**Comment by l-johnston** [comment]
Provide the LabVIEW control that led to the warning and I'll take a look.

**Comment by l-johnston** [comment]
I have tracked this deprecation warning to the Waveform Graph control that is a cluster of (t0, dt, Y) where t0 and dt are scalers and Y is a 1d array. Numpy considers this a ragged array.
![image](https://user-images.githubusercontent.com/17813788/151190510-7b9a8e10-af35-4440-9139-a2a50a99a465.png)

```python
>>> import autolv
>>> lv = autolv.App()
>>> vi = lv.open("d:/Python/autolv/tests/graph_cluster.vi")
...\autolv\datatypes.py:148: VisibleDeprecationWarning: Creating an ndarray from
ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with
different lengths or shapes) is deprecated. If you meant to do this, you must specify
'dtype=object' when creating the ndarray.
value = np.array(value)
>>>
```

**Comment by jj-github-jj** [comment]
Thanks for fixing this issue.
